export class ActfijoGestion {
    public af_codigo_interno : number;
    public asignado : string;
    public af_codigo_vnr: string;
    public af_codigo_contable : string;
    public codigo_ppye: number;
    public fechaRegistro: string;
    public tipo_partida_id : string;
    public cuenta_contable	: string;
    public estado : string;
    public descripcion_bien : string;
    public codigo_tipo_bien_vnr : number;
    public area_del_bien_vnr : string;
    public ccosto_del_bien_vnr : number;
    public codigo_asignado : string;
    public codigo_agd : number;
    public bodega_id : number;
    public codigo_marca : number;
    public codigo_modelo : number;
    public af_serie : string;
    public otras_especificaciones: string;
    public fechaCompra : string;
    public fecha_baja : string;
    public codigo_tipo_documento : number;
    public numero_documento : string;
    public codigo_proveedor : number;
    public af_valor_compra_siva : number;
    public af_valor_residual : number;
    public af_tasa_depreciacion_financ : number;
    public af_tasa_depreciacion_fiscal : number;
    public af_vida_util : number;
    public cod_departamento : number;
    public cod_municipio : number;
    public af_valor_vnr_siva : number;
    public fecha_alta : string;
    public usuario_alta : string;
    public fecha_modificacion	: string;
    public usuario_modificacion: string;
    public periodo_inicial	: string;
    public periodo_final	: string;
    public codigo_sucursal : string;
    public aplica_contabilidad : string;
    public solo_vnr : string;
    public estadoActivo : string;
    public marcaAf : string;
    public modeloAf : string;
    public cuenta_hija: string;
    public imagen_factura: string;
}
